### ISSUE TITLE
Cart drawer covering full page on initial load

### ISSUE THREAD

**Issue by olivermrbl** [medusajs/gatsby-starter-medusa-simple#11]
It seems, that the cart drawer is covering the entire page on initial load and hard refreshes. See attached image:

![image](https://user-images.githubusercontent.com/59018053/135619158-c8bdaa0e-9a11-4bba-8db8-e9a983b43523.png)

**Comment by edleeman17** [comment]
Seems to only be when the site is static too, i.e works in `yarn develop`
